name: readyset
services:
  readyset:
    image: "public.ecr.aws/readyset/readyset:latest"
    platform: linux/amd64
    expose:
      - 6033  # ReadySet Server Prometheus metrics at http://readyset:6033/metrics
      - 6034  # ReadySet Adapter Prometheus metrics at http://readyset:6034/metrics
    ports:
      # The ReadySet Adapter listen port, i.e. what your application / SQL shell connects to
      - "${RS_PORT:-3307}:${RS_PORT:-3307}"
    environment:
      DEPLOYMENT_ENV: quickstart_docker
      DB_DIR: /state
      PROMETHEUS_METRICS: true
      QUERY_CACHING: explicit
      QUERY_LOG: true
      QUERY_LOG_AD_HOC: true
      STANDALONE: true
      DEPLOYMENT: docker_compose_deployment
      LISTEN_ADDRESS: 0.0.0.0:${RS_PORT:-3307}
      UPSTREAM_DB_URL: ${RS_UPSTREAM_DB_URL:?}
      CONTROLLER_ADDRESS: 0.0.0.0
    volumes:
      - "readyset:/state"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "127.0.0.1:6033/health" ]
      interval: 2s
      timeout: 1s
      retries: 5
      start_period: 5s
  prometheus:
    image: "public.ecr.aws/readyset/readyset-prometheus:latest"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9090"]
      interval: 10s
      timeout: 2s
      retries: 5
    expose:
      - 9090
    volumes:
      - "prometheus:/prometheus"
  pushgateway:
    image: prom/pushgateway
    expose:
      - 9091
  grafana:
    image: "public.ecr.aws/readyset/readyset-grafana:latest"
    ports:
      - ${RS_GRAFANA_PORT:-4000}:${RS_GRAFANA_PORT:-4000}
    environment:
      RS_UPSTREAM_DB_URL:
      RS_PORT: ${RS_PORT:-3307}
      RS_GRAFANA_PORT: ${RS_GRAFANA_PORT:-4000}
volumes:
  prometheus: ~
  readyset: ~
