name: readyset-mysql
services:
  readyset:
    image: public.ecr.aws/readyset/readyset:latest
    platform: linux/amd64
    expose:
      - 6033  # ReadySet Server Prometheus metrics at http://readyset:6033/metrics
      - 6034  # ReadySet Adapter Prometheus metrics at http://readyset:6034/metrics
    ports:
      # The ReadySet Adapter listen port, i.e. what your application / SQL shell connects to
      - "${RS_PORT:-3307}:${RS_PORT:-3307}"
    environment:
      DEPLOYMENT_ENV: quickstart_docker
      DB_DIR: /state
      PROMETHEUS_METRICS: true
      QUERY_CACHING: explicit
      QUERY_LOG: true
      QUERY_LOG_AD_HOC: true
      STANDALONE: true
      DEPLOYMENT: docker_compose_deployment
      LISTEN_ADDRESS: 0.0.0.0:${RS_PORT:-3307}
      UPSTREAM_DB_URL: mysql://root:readyset@mysql/testdb
      CONTROLLER_ADDRESS: 0.0.0.0
    volumes:
      - "readyset:/state"
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -P3307 -uroot -preadyset"
      interval: 5s
      timeout: 2s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy
  prometheus:
    image: public.ecr.aws/readyset/readyset-prometheus:latest
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9090"]
      interval: 10s
      timeout: 2s
      retries: 5
    expose:
      - 9090
    volumes:
      - "prometheus:/prometheus"
  pushgateway:
    image: prom/pushgateway
    expose:
      - 9091
  grafana:
    image: public.ecr.aws/readyset/readyset-grafana:latest
    ports:
      - ${RS_GRAFANA_PORT:-4000}:${RS_GRAFANA_PORT:-4000}
    environment:
      RS_UPSTREAM_DB_URL: mysql://root:readyset@mysql/testdb
      RS_PORT: ${RS_PORT:-3307}
      RS_GRAFANA_PORT: ${RS_GRAFANA_PORT:-4000}
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=readyset
      - MYSQL_DATABASE=testdb
    expose:
      - 3306
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -P3306 -uroot -preadyset"
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - ./imdb-mysql.sql:/docker-entrypoint-initdb.d/imdb-mysql.sql
volumes:
  mysql: ~
  prometheus: ~
  readyset: ~
